version: '3.8'
services:
#   Container cho MySQL
   mysql:
     image: mysql:latest
     container_name: mysql-container
     environment:
       MYSQL_ROOT_PASSWORD: 12345678
       MYSQL_DATABASE: db_shose_camela
       MYSQL_USER: shose_user
       MYSQL_PASSWORD: 12345678
     ports:
       - "3307:3306"
    #  volumes:
    #    - ./mysql-data:/var/lib/mysql

#   Container cho ứng dụng Spring Boot
   springboot-app:
     image: be_service:latest
     container_name: be-service-container
     build:
       context: ./BE
     depends_on:
       - mysql
     ports:
      - "8080:8080"
     environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_shose_camela
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      SPRING_JPA_HIBERNATE_DDL_AUTO: create

  # Container cho ứng dụng ReactJS
   react-app:
     image: fe_service:latest
     container_name: fe-service-container
     build:
       context: ./FE
     ports:
      - "3000:3000"
